addSbtPlugin("com.codecommit"    % "sbt-github-actions"  % "0.10.1")
addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.2")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"            % "2.2.20")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"          % "0.4.3")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("ch.epfl.lamp"      % "sbt-dotty"           % "0.5.3")