addSbtPlugin("com.codecommit"    % "sbt-github-actions"  % "0.10.1")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"            % "2.2.20")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"          % "0.4.3")
// addSbtPlugin("ch.epfl.lamp"      % "sbt-dotty"           % "0.5.3")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"      % "1.5.7")
